package b4a.example;


import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.BALayout;
import anywheresoftware.b4a.debug.*;

public class datosglobales {
private static datosglobales mostCurrent = new datosglobales();
public static Object getObject() {
    throw new RuntimeException("Code module does not support this method.");
}
 public anywheresoftware.b4a.keywords.Common __c = null;
public static int _idusuario = 0;
public static String _codusuario = "";
public static String _descusuario = "";
public static String _nombredispositivo = "";
public static String _palabraclave = "";
public static boolean _ejecutandose = false;
public static int _segundos = 0;
public static boolean _logok = false;
public static boolean _configurando = false;
public static boolean _enprincipal = false;
public static boolean _forzarejecucion = false;
public static String _copiaporcentencurso = "";
public static String _copiacantencurso = "";
public static String _copiaprogreso = "";
public static String _copiaprogress = "";
public static String _nombrearchivo = "";
public static String _xml_usuario = "";
public static String _xml_contraseña = "";
public static String _xml_recordar = "";
public static String _xml_fotoscamara = "";
public static String _xml_videoscamara = "";
public static String _xml_imageneswhatsapp = "";
public static String _xml_videoswhatsapp = "";
public static String _xml_chfotoscamara = "";
public static String _xml_chvideoscamara = "";
public static String _xml_chimageneswhatsapp = "";
public static String _xml_chvideoswhatsapp = "";
public static String _xml_primeravez = "";
public static String _xml_usuariorutafotos = "";
public static String _xml_servidorruta = "";
public static String _xml_servidorip = "";
public static String _xml_servidorpuerto = "";
public static String _xml_servidorusuario = "";
public static String _xml_servidorclave = "";
public static String _servidorruta = "";
public static String _servidorip = "";
public static String _servidorpuerto = "";
public static String _servidorusuario = "";
public static String _servidorclave = "";
public static String _usuariorutafotos = "";
public static String _usuariorutavideos = "";
public static String _pathfotoscamara = "";
public static String _pathvideoscamara = "";
public static String _mobilrutafotoscamara = "";
public static String _mobilrutavideoscamara = "";
public static String _mobilrutaimageneswhapp = "";
public static String _mobilrutavideoswhapp = "";
public static anywheresoftware.b4a.objects.collections.List _colmobilrutaorigen = null;
public static int _indicefullbkp = 0;
public b4a.example.main _main = null;
public b4a.example.servbackup4 _servbackup4 = null;
public b4a.example.principal _principal = null;
public b4a.example.fxglobales _fxglobales = null;
public b4a.example.login _login = null;
public b4a.example.configuracion _configuracion = null;
public b4a.example.backup _backup = null;
public b4a.example.servbackup _servbackup = null;
public b4a.example.servbackup2 _servbackup2 = null;
public b4a.example.servbackup3 _servbackup3 = null;
public b4a.example.starter _starter = null;
public static String  _process_globals() throws Exception{
 //BA.debugLineNum = 3;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 10;BA.debugLine="Dim IdUsuario As Int";
_idusuario = 0;
 //BA.debugLineNum = 11;BA.debugLine="Dim CodUsuario As String";
_codusuario = "";
 //BA.debugLineNum = 12;BA.debugLine="Dim DescUsuario As String";
_descusuario = "";
 //BA.debugLineNum = 13;BA.debugLine="Dim NombreDispositivo As String";
_nombredispositivo = "";
 //BA.debugLineNum = 14;BA.debugLine="Dim PalabraClave As String = \"aMaPoLa_2970\"";
_palabraclave = "aMaPoLa_2970";
 //BA.debugLineNum = 16;BA.debugLine="Dim Ejecutandose As Boolean";
_ejecutandose = false;
 //BA.debugLineNum = 17;BA.debugLine="Dim Segundos As Int = 3600  '3600 '20 estaba cada";
_segundos = (int) (3600);
 //BA.debugLineNum = 19;BA.debugLine="Dim LogOk As Boolean";
_logok = false;
 //BA.debugLineNum = 20;BA.debugLine="Dim Configurando As Boolean 'si en backup o login";
_configurando = false;
 //BA.debugLineNum = 21;BA.debugLine="Dim EnPrincipal As Boolean";
_enprincipal = false;
 //BA.debugLineNum = 22;BA.debugLine="Dim ForzarEjecucion As Boolean";
_forzarejecucion = false;
 //BA.debugLineNum = 25;BA.debugLine="Dim CopiaPorcentEnCurso As String";
_copiaporcentencurso = "";
 //BA.debugLineNum = 26;BA.debugLine="Dim CopiaCantEnCurso As String";
_copiacantencurso = "";
 //BA.debugLineNum = 27;BA.debugLine="Dim CopiaProgreso As String";
_copiaprogreso = "";
 //BA.debugLineNum = 28;BA.debugLine="Dim CopiaProgress As String";
_copiaprogress = "";
 //BA.debugLineNum = 30;BA.debugLine="Dim NombreArchivo As String";
_nombrearchivo = "";
 //BA.debugLineNum = 38;BA.debugLine="Dim XML_Usuario As String";
_xml_usuario = "";
 //BA.debugLineNum = 39;BA.debugLine="Dim XML_Contraseña As String";
_xml_contraseña = "";
 //BA.debugLineNum = 40;BA.debugLine="Dim XML_Recordar As String '0/1";
_xml_recordar = "";
 //BA.debugLineNum = 43;BA.debugLine="Dim XML_FotosCamara As String";
_xml_fotoscamara = "";
 //BA.debugLineNum = 44;BA.debugLine="Dim XML_VideosCamara As String";
_xml_videoscamara = "";
 //BA.debugLineNum = 45;BA.debugLine="Dim XML_ImagenesWhatsApp As String";
_xml_imageneswhatsapp = "";
 //BA.debugLineNum = 46;BA.debugLine="Dim XML_VideosWhatsApp As String";
_xml_videoswhatsapp = "";
 //BA.debugLineNum = 47;BA.debugLine="Dim XML_ChFotosCamara As String";
_xml_chfotoscamara = "";
 //BA.debugLineNum = 48;BA.debugLine="Dim XML_ChVideosCamara As String";
_xml_chvideoscamara = "";
 //BA.debugLineNum = 49;BA.debugLine="Dim XML_ChImagenesWhatsApp As String";
_xml_chimageneswhatsapp = "";
 //BA.debugLineNum = 50;BA.debugLine="Dim XML_ChVideosWhatsApp As String";
_xml_chvideoswhatsapp = "";
 //BA.debugLineNum = 51;BA.debugLine="Dim XML_PrimeraVez As String";
_xml_primeravez = "";
 //BA.debugLineNum = 54;BA.debugLine="Dim XML_UsuarioRutaFotos As String";
_xml_usuariorutafotos = "";
 //BA.debugLineNum = 57;BA.debugLine="Dim XML_ServidorRuta As String";
_xml_servidorruta = "";
 //BA.debugLineNum = 58;BA.debugLine="Dim XML_ServidorIp As String";
_xml_servidorip = "";
 //BA.debugLineNum = 59;BA.debugLine="Dim XML_ServidorPuerto As String";
_xml_servidorpuerto = "";
 //BA.debugLineNum = 60;BA.debugLine="Dim XML_ServidorUsuario As String";
_xml_servidorusuario = "";
 //BA.debugLineNum = 61;BA.debugLine="Dim XML_ServidorClave As String";
_xml_servidorclave = "";
 //BA.debugLineNum = 70;BA.debugLine="Dim ServidorRuta As String '= \"./H/DiscoCompart";
_servidorruta = "";
 //BA.debugLineNum = 71;BA.debugLine="Dim ServidorIp As String '= \"192.168.1.112\"  '--";
_servidorip = "";
 //BA.debugLineNum = 72;BA.debugLine="Dim ServidorPuerto As String '= \"21\"  '--> Ya se";
_servidorpuerto = "";
 //BA.debugLineNum = 73;BA.debugLine="Dim ServidorUsuario As String '= \"admin\"  '--> Y";
_servidorusuario = "";
 //BA.debugLineNum = 74;BA.debugLine="Dim ServidorClave As String '= \"31119914\"  '-->";
_servidorclave = "";
 //BA.debugLineNum = 79;BA.debugLine="Dim UsuarioRutaFotos As String '= ServidorRuta &";
_usuariorutafotos = "";
 //BA.debugLineNum = 82;BA.debugLine="Dim UsuarioRutaVideos As String  '= ServidorRuta";
_usuariorutavideos = "";
 //BA.debugLineNum = 94;BA.debugLine="Dim const PathFotosCamara As String = \"Fotos\"";
_pathfotoscamara = "Fotos";
 //BA.debugLineNum = 95;BA.debugLine="Dim const PathVideosCamara As String = \"Videos\"";
_pathvideoscamara = "Videos";
 //BA.debugLineNum = 122;BA.debugLine="Dim MobilRutaFotosCamara As String '=  \"/sdcard/P";
_mobilrutafotoscamara = "";
 //BA.debugLineNum = 123;BA.debugLine="Dim MobilRutaVideosCamara As String ' =  \"/sdcard";
_mobilrutavideoscamara = "";
 //BA.debugLineNum = 125;BA.debugLine="Dim MobilRutaImagenesWhapp As String";
_mobilrutaimageneswhapp = "";
 //BA.debugLineNum = 126;BA.debugLine="Dim MobilRutaVideosWhapp As String";
_mobilrutavideoswhapp = "";
 //BA.debugLineNum = 135;BA.debugLine="Dim ColMobilRutaOrigen As List";
_colmobilrutaorigen = new anywheresoftware.b4a.objects.collections.List();
 //BA.debugLineNum = 167;BA.debugLine="Dim IndiceFullBkp As Int";
_indicefullbkp = 0;
 //BA.debugLineNum = 170;BA.debugLine="End Sub";
return "";
}
}
